'use strict';

import { QueryInterface, Sequelize, QueryTypes } from 'sequelize';
import { v4 as uuidv4 } from 'uuid';

/** @type {import('sequelize-cli').Migration} */
export default {
  async up(queryInterface: QueryInterface, sequelize: Sequelize) {
    // Ambil Referensi ID dari tabel wali/orang tua jika ada
    const walis: any = await queryInterface.sequelize.query(
      'SELECT id_wali FROM orang_tua_wali LIMIT 1',
      { type: QueryTypes.SELECT }
    );

    // Ambil Referensi ID dari tabel institusi/institution
    const institutions: any = await queryInterface.sequelize.query(
      'SELECT id_institution, institution_name FROM institution LIMIT 1',
      { type: QueryTypes.SELECT }
    );

    if (!institutions || institutions.length === 0) {
      console.error('Gagal: Tabel institution wajib terisi terlebih dahulu.');
      return;
    }

    // Set fallback id_wali jika tabel wali ternyata masih kosong
    const targetWaliId = walis.length > 0 ? walis[0].id_wali : uuidv4();

    // Ambil data institusi untuk disamakan ke id_cabang
    const targetInstitutionId = institutions[0].id_institution;
    const targetInstitutionName =
      institutions[0].institution_name || 'Pondok Pesantren Pusat';

    // Masukkan 10 data santri dummy ke tabel 'santri'
    return queryInterface.bulkInsert('santri', [
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Muhammad Reyhan',
        nis: '20260001',
        nik: '3201011234560003',
        gender: 'L',
        birth_place: 'Jakarta',
        birth_date: '2011-03-20',
        phone: '081299998888',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2026',
        group_code_2: 'KELAS-7A',
        group_code_3: 'ASRAMA-A01',
        nomor_nasabah: 'NSB-001234',
        kartu_santri_nomor: 'KRT-26001',
        kartu_santri: 'https://link-foto-kartu.com/reyhan.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Aisyah Putri',
        nis: '20260002',
        nik: '3201016543210004',
        gender: 'P',
        birth_place: 'Bogor',
        birth_date: '2012-07-14',
        phone: '085711112222',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2026',
        group_code_2: 'KELAS-7B',
        group_code_3: 'ASRAMA-B04',
        nomor_nasabah: 'NSB-001235',
        kartu_santri_nomor: 'KRT-26002',
        kartu_santri: 'https://link-foto-kartu.com/aisyah.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Ahmad Rafif',
        nis: '20260003',
        nik: '3202111209990001',
        gender: 'L',
        birth_place: 'Bandung',
        birth_date: '2010-11-05',
        phone: '081344445555',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2025',
        group_code_2: 'KELAS-8A',
        group_code_3: 'ASRAMA-A02',
        nomor_nasabah: 'NSB-001236',
        kartu_santri_nomor: 'KRT-25043',
        kartu_santri: 'https://link-foto-kartu.com/rafif.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif - Pengurus OSIS',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Fatima Azzahra',
        nis: '20260004',
        nik: '3273054102110005',
        gender: 'P',
        birth_place: 'Surabaya',
        birth_date: '2011-02-10',
        phone: '089677773333',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2026',
        group_code_2: 'KELAS-7B',
        group_code_3: 'ASRAMA-B02',
        nomor_nasabah: 'NSB-001237',
        kartu_santri_nomor: 'KRT-26004',
        kartu_santri: 'https://link-foto-kartu.com/fatima.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Zainuddin Abdillah',
        nis: '20260005',
        nik: '3171021508100002',
        gender: 'L',
        birth_place: 'Semarang',
        birth_date: '2010-08-15',
        phone: '082188889999',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2025',
        group_code_2: 'KELAS-8B',
        group_code_3: 'ASRAMA-A03',
        nomor_nasabah: 'NSB-001238',
        kartu_santri_nomor: 'KRT-25088',
        kartu_santri: 'https://link-foto-kartu.com/zainuddin.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Yusuf Al-Ghifari',
        nis: '20260006',
        nik: '3201012211100009',
        gender: 'L',
        birth_place: 'Yogyakarta',
        birth_date: '2011-05-12',
        phone: '081233445566',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2026',
        group_code_2: 'KELAS-7A',
        group_code_3: 'ASRAMA-A01',
        nomor_nasabah: 'NSB-001239',
        kartu_santri_nomor: 'KRT-26006',
        kartu_santri: 'https://link-foto-kartu.com/yusuf.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Khadijah Humaira',
        nis: '20260007',
        nik: '3276025501120008',
        gender: 'P',
        birth_place: 'Depok',
        birth_date: '2012-01-15',
        phone: '085699887766',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2026',
        group_code_2: 'KELAS-7B',
        group_code_3: 'ASRAMA-B04',
        nomor_nasabah: 'NSB-001240',
        kartu_santri_nomor: 'KRT-26007',
        kartu_santri: 'https://link-foto-kartu.com/khadijah.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Ibrahim Malik',
        nis: '20260008',
        nik: '3174030504110001',
        gender: 'L',
        birth_place: 'Jakarta Selatan',
        birth_date: '2011-04-05',
        phone: '087811223344',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2026',
        group_code_2: 'KELAS-7A',
        group_code_3: 'ASRAMA-A02',
        nomor_nasabah: 'NSB-001241',
        kartu_santri_nomor: 'KRT-26008',
        kartu_santri: 'https://link-foto-kartu.com/ibrahim.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Safiyya Nabila',
        nis: '20260009',
        nik: '3578014509110004',
        gender: 'P',
        birth_place: 'Malang',
        birth_date: '2011-09-05',
        phone: '081955667788',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2026',
        group_code_2: 'KELAS-7B',
        group_code_3: 'ASRAMA-B02',
        nomor_nasabah: 'NSB-001242',
        kartu_santri_nomor: 'KRT-26009',
        kartu_santri: 'https://link-foto-kartu.com/safiyya.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
      {
        id_santri: uuidv4(),
        id_wali: targetWaliId,
        fullname: 'Ali Zainal Abidin',
        nis: '20260010',
        nik: '3374112210100007',
        gender: 'L',
        birth_place: 'Solo',
        birth_date: '2010-10-22',
        phone: '082244556677',
        id_cabang: targetInstitutionId,
        nama_cabang: targetInstitutionName,
        id_institution: targetInstitutionId,
        institution_name: targetInstitutionName,
        group_code_1: 'ANGKATAN-2025',
        group_code_2: 'KELAS-8B',
        group_code_3: 'ASRAMA-A03',
        nomor_nasabah: 'NSB-001243',
        kartu_santri_nomor: 'KRT-25091',
        kartu_santri: 'https://link-foto-kartu.com/ali.jpg',
        status: 1,
        keterangan: 'Santri Mukim Aktif',
        created_at: new Date(),
        updated_at: new Date(),
        id_santri_sitrendi: uuidv4(),
        id_wali_sitrendi: uuidv4(),
        institution_id_sitrendi: uuidv4(),
      },
    ]);
  },

  async down(queryInterface: QueryInterface) {
    return queryInterface.bulkDelete('santri', {}, {});
  },
};
